# Generated by Django 5.2.7 on 2025-11-06 05:35

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or summary of the clinical guideline', max_length=500)),
                ('content', models.TextField(help_text='Full text content of the clinical guideline')),
                ('source', models.CharField(db_index=True, help_text="Source organization (e.g., 'AHA', 'ACC', 'WHO', 'UpToDate')", max_length=255)),
                ('category', models.CharField(db_index=True, help_text="Medical category (e.g., 'cardiology', 'diabetes', 'hypertension')", max_length=100)),
                ('subcategory', models.CharField(blank=True, help_text='More specific subcategory', max_length=100, null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, help_text='Vector embedding for semantic similarity search')),
                ('year', models.IntegerField(blank=True, help_text='Publication year', null=True)),
                ('url', models.URLField(blank=True, help_text='URL to original source', null=True)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='List of keywords for filtering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this guideline was retrieved')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this guideline was retrieved', null=True)),
            ],
            options={
                'verbose_name': 'Clinical Guideline',
                'verbose_name_plural': 'Clinical Guidelines',
                'db_table': 'clinical_guidelines',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'source'], name='clinical_gu_categor_0903bf_idx'), models.Index(fields=['-created_at'], name='clinical_gu_created_f92fa2_idx'), models.Index(fields=['-usage_count'], name='clinical_gu_usage_c_67a3e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PHIDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entity_type', models.CharField(help_text="Type of PHI detected (e.g., 'PERSON', 'PHONE_NUMBER')", max_length=50)),
                ('field_name', models.CharField(help_text="Field where PHI was detected (e.g., 'symptoms', 'medical_history')", max_length=100)),
                ('is_output_leak', models.BooleanField(default=False, help_text='Whether PHI was detected in AI output (concerning!)')),
                ('confidence_score', models.FloatField(help_text='Confidence score of detection (0-1)')),
                ('text_length', models.IntegerField(help_text='Length of text that was scanned')),
                ('position_start', models.IntegerField(help_text='Start position of detected entity')),
                ('position_end', models.IntegerField(help_text='End position of detected entity')),
                ('session_id', models.CharField(blank=True, help_text='Session or request ID for grouping detections', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'PHI Detection Log',
                'verbose_name_plural': 'PHI Detection Logs',
                'db_table': 'phi_detection_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='phi_detecti_timesta_6ff8a8_idx'), models.Index(fields=['entity_type'], name='phi_detecti_entity__51480d_idx'), models.Index(fields=['is_output_leak'], name='phi_detecti_is_outp_31caa7_idx')],
            },
        ),
    ]
