# Generated by Django 5.2.13 on 2026-07-14 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_gpt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('0-15', '0-15'), ('18-30', '18-30'), ('31-45', '31-45'), ('46-60', '46-60'), ('61-75', '61-75'), ('75+', '75+')], db_index=True, max_length=10)),
                ('biological_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('weight_kg', models.FloatField(help_text='Most recent known weight in kg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('hr_bpm', models.IntegerField()),
                ('oxygen_spo2_pct', models.FloatField()),
                ('respiratory_rate_bpm', models.IntegerField()),
                ('sbp_mmhg', models.IntegerField()),
                ('dbp_mmhg', models.IntegerField()),
                ('glucose_mgdl', models.FloatField(blank=True, null=True)),
                ('cholesterol_mgdl', models.FloatField(blank=True, null=True)),
                ('hemoglobin_gdl', models.FloatField(blank=True, null=True)),
                ('temperature_f', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, help_text='Device-measured weight at time of reading (distinct from Patient.weight_kg)', null=True)),
                ('step_count', models.IntegerField(blank=True, null=True)),
                ('ecg', models.BooleanField(default=False)),
                ('stethoscope', models.BooleanField(default=False)),
                ('fall_detected', models.BooleanField(default=False)),
                ('alert_count', models.IntegerField(default=0)),
                ('highest_severity', models.CharField(choices=[('none', 'None'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='none', max_length=10)),
                ('has_alert', models.BooleanField(db_index=True, default=False, help_text='alert_count > 0 — used to exclude abnormal readings from the Historical SD baseline calculation')),
                ('alerts', models.JSONField(blank=True, default=list, help_text='Full alerts list from RuleEngineService.evaluate() — messages, severity, threshold_basis per parameter')),
                ('risk_label', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, help_text='Derived 1:1 from highest_severity for seed/training data; ML-predicted for live readings once XGBoost is wired in', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_readings', to='clin_gpt.patient')),
            ],
            options={
                'verbose_name': 'Vital Reading',
                'verbose_name_plural': 'Vital Readings',
                'db_table': 'vital_readings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.DeleteModel(
            name='ClinicalGuideline',
        ),
        migrations.DeleteModel(
            name='PHIDetectionLog',
        ),
        migrations.AddIndex(
            model_name='vitalreading',
            index=models.Index(fields=['patient', '-recorded_at'], name='vital_readi_patient_800333_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalreading',
            index=models.Index(fields=['patient', 'has_alert', '-recorded_at'], name='vital_readi_patient_1ce1f0_idx'),
        ),
    ]
