# Generated by Django 5.2.13 on 2026-07-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_gpt', '0002_patient_vitalreading_delete_clinicalguideline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalreading',
            name='source_case_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='case_id from the authored seed JSON (all_100_cases.json). Null for real live readings. Lets the seed command be re-run safely without creating duplicates.', null=True, unique=True),
        ),
    ]
