# Generated by Django 5.2.13 on 2026-07-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_gpt', '0003_vitalreading_source_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='external_patient_ref',
            field=models.CharField(blank=True, db_index=True, help_text="Identifier from the external device_vitals_raw source (watch/app team's patient ID). Null for seed-only patients. Lets repeat live readings resolve to the same Patient row.", max_length=100, null=True, unique=True),
        ),
    ]
